# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Load ASC API Key information to use in subsequent lanes"
#   lane :load_asc_api_key do
#     if is_ci
#       api_key = app_store_connect_api_key(
#         issuer_id: ENV["ASC_ISSUER_ID"],
#         key_content: ENV["ASC_KEY"],
#         key_id: ENV["ASC_KEY_ID"],
#       )
#     else
#       api_key = app_store_connect_api_key(
#         issuer_id: ENV["ASC_ISSUER_ID"],
#         key_filepath: "~/Downloads/asc-key.p8",
#         key_id: ENV["ASC_KEY_ID"],
#       )
#     end
#   end
  api_key = app_store_connect_api_key(
        issuer_id: ENV["ASC_ISSUER_ID"],
        key_content: ENV["ASC_KEY"],
        key_id: ENV["ASC_KEY_ID"],
        duration: 1200,            
        in_house: false
  )

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Yeshivat Torat Shraga.xcodeproj")
#     match(type: "appstore", app_identifier: "com.reesedevelopment.YTS.NotificationService")
#     match(type: "appstore", app_identifier: "com.reesedevelopment.YTS")
    
#     match(
#       type: 'appstore',
#       app_identifier: "com.reesedevelopment.YTS.NotificationService",
#       api_key: api_key
#     )
    
#     match(
#       type: 'appstore',
#       app_identifier: "com.reesedevelopment.YTS",
#       api_key: api_key
#     )
    
#     target_to_profile_mapping = {
#       "Yeshivat Torat Shraga" => "match AppStore com.reesedevelopment.YTS",
#       "NotificationModifier" => "match AppStore com.reesedevelopment.YTS.NotificationService",
#     }

#     target_to_profile_mapping.each do |target, profile_name|
#       update_code_signing_settings(
#         targets: [target],
#         build_configurations: ["Release"],
#         profile_name: profile_name,
#       )
#     end

#     gym(
#       export_method: "app-store",
#       scheme: "Yeshivat Torat Shraga",
#        export_options: {
#         method: "app-store",
#         provisioningProfiles: lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING],
#         signing_style: "manual",
#       },
#       skip_profile_detection: true,
#     )
#     upload_to_app_store
  end
end
