# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

lane :build do
  desc "Build the app"
  # Step one: Get the app identifier from the Appfile
  app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

  # Step two: Get the API key from the lane context
  api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
  
  # Step three: Use the API key to download the provisioning profiles and certificates

  # Use match to download the provisioning profiles and certificates
  # (Because the app has an extension, we need to do this for the main app and the extension)
  match(
    force: false,
    api_key: api_key,
    git_basic_authorization: Base64.strict_encode64(ENV["MATCH_GIT_BASIC_AUTHORIZATION"]),
    type: "appstore",
    readonly: true,
    app_identifier: [app_identifier]
  )
  match(
    force: false,
    api_key: api_key,
    git_basic_authorization: Base64.strict_encode64(ENV["MATCH_GIT_BASIC_AUTHORIZATION"]),
    type: "appstore",
    readonly: true,
    app_identifier: ["#{app_identifier}.NotificationService"]
  )

  # Step four: Build the app
  gym(
    project: "iOS/Yeshivat Torat Shraga.xcodeproj",
    scheme: "Yeshivat Torat Shraga",
    clean: false,
    include_bitcode: false,
    export_method: "app-store",
    export_options: {
      signingStyle: "manual",
      provisioningProfiles: {
        "#{app_identifier}": "match AppStore #{app_identifier}",
        "#{app_identifier}.NotificationService": "match AppStore #{app_identifier}.NotificationService"
      }
    }
  )
end





lane :load_api_key do
  desc "Load ASC API Key information to use in subsequent lanes"
  if is_ci
    api_key = app_store_connect_api_key(
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY"],
      key_id: ENV["ASC_KEY_ID"],
      is_key_content_base64: true,
      duration: 1200,            
      in_house: false
    )
  else
    api_key = app_store_connect_api_key(
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: "~/Downloads/asc-key.p8",
      key_id: ENV["ASC_KEY_ID"],
    )
  end
end
