# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 deploy:
   if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v2
 
     - name: Set up ruby env
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: 2.7.2
         bundler-cache: true
 
    #  - name: Import Code-Signing Certificates
    #    uses: Apple-Actions/import-codesign-certs@v1
    #    with:
    #      p12-file-base64: ${{ secrets.IOS_DIST_SIGNING_KEY }}
    #      p12-password: ${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}
    
     - name: Build & upload iOS binary
       run: bundle exec fastlane build_upload_testflight
       env:
         ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
         ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
         ASC_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
         MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
         KEYCHAIN_PATH: ~/Library/Keychains/signing_temp.keychain-db
 
     - name: Upload app-store ipa and dsyms to artifacts
       uses: actions/upload-artifact@v2
       with:
         name: app-store ipa & dsyms
         path: |
           ${{ github.workspace }}/example-iOS.ipa
           ${{ github.workspace }}/*.app.dSYM.zip
